pythonver: '2.7'
miniconda_url: https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
include:
  - runtime_configs/minimal_2.7.yaml
conda:
    install:
      - numpy
      - numba
      - pandas
      - pytz
pip:
    install:
      - glob2
      - boto
      - prophet
    upgrade:
      - cloudpickle
      - enum34

extracmds:
  - "ls -lah"
